### ISSUE TITLE
Apply style in excel.

### ISSUE THREAD

**Issue by pjain9390** [clarketm/TableExport#19] opened 2016-09-09 09:47 UTC
I am generating the XLSX formate of excel , I want to use same style which I have received from HTML string.
 Please suggest Its important for me.

**Comment by clarketm** [comment] 2016-10-01 04:23
I am closing this issue as a duplicate of: 
> **#12: How to apply styles to excel file?**

**Comment by clarketm** [comment] 2016-10-01 04:24
I am closing this issue as a duplicate of: 
> **#12: How to apply styles to excel file?**

**Closed by clarketm** 2016-10-01 04:24 UTC
Labels: duplicate
