### ISSUE TITLE
Not able to export TH

### ISSUE THREAD

**Issue by g21wadhwa** [clarketm/TableExport#14] opened 2016-08-08 15:41 UTC
Please advise.

**Comment by clarketm** [comment] 2016-08-10 20:48
@g21wadhwa, can you please provide a more detailed explanation of your particular issue? What does your html structure look like?

**Comment by g21wadhwa** [comment] 2016-08-10 21:45
<table class="pvtTable" id="example-table" border="1" data-numrows="17" data-numcols="5"><tbody><tr><td colspan="2" rowspan="1"></td><td class="pvtAxisLabel">Industry</td><td class="pvtColLabel" colspan="1" rowspan="2">Airport</td><td class="pvtColLabel" colspan="1" rowspan="2">Build America Bonds</td><td class="pvtColLabel" colspan="1" rowspan="2">Development</td><td class="pvtColLabel" colspan="1" rowspan="2">Education</td><td class="pvtColLabel" colspan="1" rowspan="2">Facilities</td><td class="pvtTotalLabel" rowspan="2">Totals</td></tr><tr><td class="pvtAxisLabel">State</td><td class="pvtAxisLabel">Sector</td><td></td></tr></tbody><tbody><tr><td class="pvtRowLabel" rowspan="14">CA</td><td class="pvtRowLabel" rowspan="1" colspan="2">ARPT</td><td class="pvtVal row2 col0" data-value="205080"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;ARPT&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Airport&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">205,080.00</span></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="205080" data-for="row2">205,080.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">CMNTYCLG</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="40001"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;CMNTYCLG&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Build America Bonds&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">40,001.00</span></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="40001" data-for="row2">40,001.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">DEV</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="453444"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;DEV&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Development&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">453,444.00</span></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="453444" data-for="row2">453,444.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">GO</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="857841"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;GO&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Build America Bonds&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">857,841.00</span></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="857841" data-for="row2">857,841.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">GOVLEASE</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="5935"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;GOVLEASE&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Facilities&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">5,935.00</span></td><td class="pvtTotal rowTotal" data-value="5935" data-for="row2">5,935.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">HOSP</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="7570"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;HOSP&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Development&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">7,570.00</span></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="7570" data-for="row2">7,570.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">LNPOOL</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="43585"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;LNPOOL&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Education&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">43,585.00</span></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="43585" data-for="row2">43,585.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">MEL</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="10002"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;MEL&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Education&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">10,002.00</span></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="10002" data-for="row2">10,002.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">PUBPWR</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="10590"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;PUBPWR&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Build America Bonds&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">10,590.00</span></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="10590" data-for="row2">10,590.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">PVTS</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="26301"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;PVTS&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Education&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">26,301.00</span></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="26301" data-for="row2">26,301.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">SCD</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="8125"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;SCD&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Build America Bonds&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">8,125.00</span></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="8125" data-for="row2">8,125.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">TIF</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="10000"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;TIF&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Development&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">10,000.00</span></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="10000" data-for="row2">10,000.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">TOLL</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="20000"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;TOLL&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Build America Bonds&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">20,000.00</span></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="20000" data-for="row2">20,000.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">WTRSWR</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="5000"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CA&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;WTRSWR&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Build America Bonds&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">5,000.00</span></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="5000" data-for="row2">5,000.00</td></tr><tr><td class="pvtRowLabel" rowspan="3">CO</td><td class="pvtRowLabel" rowspan="1" colspan="2">ARPT</td><td class="pvtVal row2 col0" data-value="44670"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CO&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;ARPT&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Airport&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">44,670.00</span></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="44670" data-for="row2">44,670.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">EDU</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="null"></td><td class="pvtVal row2 col3" data-value="270100"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CO&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;EDU&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Education&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">270,100.00</span></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="270100" data-for="row2">270,100.00</td></tr><tr><td class="pvtRowLabel" rowspan="1" colspan="2">MISCTAX</td><td class="pvtVal row2 col0" data-value="null"></td><td class="pvtVal row2 col1" data-value="null"></td><td class="pvtVal row2 col2" data-value="5001"><span title="Double Click to view details" ondblclick="viewCellDetails({&quot;rowData&quot;:[{&quot;key&quot;:&quot;state&quot;,&quot;value&quot;:&quot;CO&quot;},{&quot;key&quot;:&quot;bbg_Sector&quot;,&quot;value&quot;:&quot;MISCTAX&quot;}],&quot;colData&quot;:[{&quot;key&quot;:&quot;industryType&quot;,&quot;value&quot;:&quot;Development&quot;}],&quot;filterInclusions&quot;:{&quot;State&quot;:[&quot;CA&quot;,&quot;CO&quot;],&quot;Industry&quot;:[&quot;Airport&quot;,&quot;Build America Bonds&quot;,&quot;Development&quot;,&quot;Education&quot;,&quot;Facilities&quot;]}})">5,001.00</span></td><td class="pvtVal row2 col3" data-value="null"></td><td class="pvtVal row2 col4" data-value="null"></td><td class="pvtTotal rowTotal" data-value="5001" data-for="row2">5,001.00</td></tr><tr><td class="pvtTotalLabel" colspan="3">Totals</td><td class="pvtTotal colTotal" data-value="249750" data-for="col0">249,750.00</td><td class="pvtTotal colTotal" data-value="941557" data-for="col1">941,557.00</td><td class="pvtTotal colTotal" data-value="476015" data-for="col2">476,015.00</td><td class="pvtTotal colTotal" data-value="349988" data-for="col3">349,988.00</td><td class="pvtTotal colTotal" data-value="5935" data-for="col4">5,935.00</td><td class="pvtGrandTotal" data-value="2023245">2,023,245.00</td></tr></tbody></table>

**Comment by clarketm** [comment] 2016-08-11 00:13
It appears that the issue has to do with the usage of `colspan` and `rowspan` attributes in your table markup. Unfortunately, TableExport does not support cell merging (issue #11). The good news is that this is on my TODO list.  I hope to get this feature out before the next release.

> I am closing this issue as a duplicate of **issue #11: support for cell merge? (colspan, rowspan)**

**Comment by clarketm** [comment] 2016-08-11 00:14
I am closing this issue as a duplicate of: 
> **#11: support for cell merge? (colspan, rowspan)**

**Comment by clarketm** [comment] 2016-08-11 00:15
I am closing this issue as a duplicate of: 
> **#11: support for cell merge? (colspan, rowspan)**

**Closed by clarketm** 2016-08-11 00:15 UTC
Labels: duplicate
